name: hello-world
on: push
jobs:
  my-job:
    runs-on: ubuntu-latest
    steps: A
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/clockbox:latest
  modify_image_tag:
    needs: build_and_push_image
    runs-on: ubuntu-latest
    dependsOn: A
    steps: B
      - 
        uses: actions/checkout@v3
        name: Changing the deployment of git repo
        with:
          repository: repo-link
          token: ${{ secrets.GIT_TOKEN }}
          ref: branch-to-pull
      - name: modify the image
        run: |
          git config user.email ${{ secrets.email }}
          git config user.name ${{ secrets.name }}
          echo “Working Directory: $(pwd)”
         
          # Navigate to the specific Helm chart directory
          cd helm-chart-dir
           
          # Print values.yaml for debugging before changes
          echo “Before modification:”
          cat values.yaml
           
          sed -i ‘/^image:/,/^ tag:/{s/^ tag: .*/ tag: “'$ENVIRONMENT'-’$RUN_NUMBER’”/}’ values.yaml
           
          # Print values.yaml for debugging after changes
          echo “After modification:”
          cat values.yaml
           
          git add values.yaml
          git commit -m “Update image tag by Github Actions Job change manifest: ${{ github.run_number }}”
          git push origin dev
        env:
          GIT_USERNAME: ${{ secrets.GIT_USERNAME }}
          GIT_PASSWORD: ${{ secrets.GIT_TOKEN }}
          RUN_NUMBER: ${{ github.run_number }}
          ENVIRONMENT: ${{ vars.ENVIRONMENT }}
